[package]
name = "instafetcher"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
open = "2.1.2"
serde = { version = "1.0.137", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
