name: Rust
on: [push, pull_request]
env:
  CARGO_DISPLAY_OPTS: --color=always
  CARGO_BUILD_OPTS: --release

  INSTAGRAM_APP_ID: ${{ secrets.INSTAGRAM_APP_ID }}
  INSTAGRAM_APP_SECRET: ${{ secrets.INSTAGRAM_APP_SECRET }}
  INSTAGRAM_OAUTH_URI: ${{ secrets.INSTAGRAM_OAUTH_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile a package
        run: cargo build $CARGO_DISPLAY_OPTS $CARGO_BUILD_OPTS --all-targets

      - name: Build documentation
        run: cargo doc $CARGO_DISPLAY_OPTS $CARGO_BUILD_OPTS

      - name: Test
        run: cargo test $CARGO_DISPLAY_OPTS $CARGO_BUILD_OPTS --all-targets

  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Install SARIF tools
        run: cargo install $CARGO_DISPLAY_OPTS clippy-sarif sarif-fmt

      - name: Perform analysis
        run:
          cargo clippy $CARGO_DISPLAY_OPTS $CARGO_BUILD_OPTS
                --all-targets --all-features --message-format=json |
                clippy-sarif | tee clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: clippy-results.sarif
          wait-for-processing: true
